### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by akaStiX** [premake/premake-core#65] opened 2015-05-12 00:10 UTC
Tried to run tests, this is the output from the latest premake version:
```
Running action 'test'...
xcode_project.XCBuildConfigurationTarget_OnInfoPlist: ...emakeFork/modules/xcode/tests/test_xcode_project.lua:1010: (8) expected:
				INFOPLIST_FILE = "../../MyProject-Info.plist";
...but was:
				INFOPLIST_FILE = "D:/MyProject-Info.plist";
stack traceback:
	...emakeFork/modules/xcode/tests/test_xcode_project.lua:1010: in function <...emakeFork/modules/xcode/tests/test_xcode_project.lua:992>
vstudio_vs2010_rule_vars.onPathVar: ...Fork/tests/actions/vstudio/vc2010/test_rule_vars.lua:108: (2) expected:
	<MyVar>..\..\path\to\file</MyVar>
...but was:
	<MyVar>D:\path\to\file</MyVar>
stack traceback:
	...Fork/tests/actions/vstudio/vc2010/test_rule_vars.lua:108: in function <...Fork/tests/actions/vstudio/vc2010/test_rule_vars.lua:100>
running time : 2.562
1149 tests passed, 2 failed
```
Do you run them on Travis-CI?

**Comment by moomalade** [comment] 2015-06-06 03:55
I can't repro this from master 7965886fb06324435be08b2fdf8e7ee5f61c7187 on either Windows or OSX.

**Comment by starkos** [comment] 2015-06-16 21:17
I'm unable to reproduce this either. Are you still having issues with this?

**Comment by samsinsane** [comment] 2015-10-08 12:43
Closing this as there hasn't been a response in almost four months. If you're still experiencing problems, please feel free to reopen the issue.

**Closed by samsinsane** 2015-10-08 12:43 UTC

**Comment by akaStiX** [comment] 2015-10-23 19:02
It's totally weird, but this is still an issue I can reproduce

**Comment by samsinsane** [comment] 2015-10-26 01:01
Looking at the test, a relative path is provided and then expected but it's translating to an absolute path, this implies to me that you've got changes in your xcode submodule, or it's outdated.
