### ISSUE TITLE
Issues with new --Wl,--start-group GCC flags

### ISSUE THREAD

**Issue by starkos** [premake/premake-core#351] opened 2015-12-02 00:46 UTC
Pull request #273 is causing issues here. We use GCC- and Clang-based linkers that are customized for specific platforms, and which don't all support the `--start-group` and `--end-group` flags. We also build for some of these platforms via Visual Studio (with custom extensions) and these flags end up in the `<AdditionalDependencies>` element, where they do not belong.

As written, there is no good way to turn the flags off without a copy-and-paste of the entire `getlinks()` function. Would it be possible to give this a rethink?

The *right* solution is to have separate tool adapters for the compiler and the linker. This is on my short list of things to address but it's a big job, and I need to get caught up to premake-core before I can begin contributing again.

At the very least it seems like we should be limiting the application to GCC specifically, and not applying them to Clang.

**Comment by TurkeyMan** [comment] 2015-12-02 02:43
Yeah, it's definitely a hack! If I recall, Tom encouraged me to commit, and said he'd offer a patch for OSX, but I it mustn't have come up.
It's a bit awkward with the current architecture. As a stop-gap, we could make an API to enable this, and maybe default it to 'on' if appropriate conditions are detected... I'd like to find a 'proper' solution though.

Does this not affect Clang? I didn't think Clang linked differently than GCC by default?

**Comment by starkos** [comment] 2015-12-02 11:22
Tom did add a clause for OS X (I assume that was him anyway) and that works fine. But I need it to work with other platforms/linkers as well.

Half wondering if I can just tear out a separate linker adapter and add compiler() and linker() replacements for toolset()…but I know there are 100 side effects that I'm not considering…

**Comment by tvandijck** [comment] 2015-12-02 16:49
I remember thinking about the toolset vs compiler/linker a while ago as I was experimenting with a "build" action module, which just invoked the compiler/linker directly.... kind of goes against the idea or "Pre-make" as it actually just "makes"... but it was an interesting experiment nonetheless.

Anyway, it would have made things quite a bit cleaner/easier if I had separated compiler and linker classes. More importantely however is the fact that the toolset is not consistently used everywhere in the vcxproj/gmake back-ends... some things are manually calculated in those backend, and so for my "build" module I had to basically redo all those things... I think we can definitely make that better.

**Comment by TurkeyMan** [comment] 2015-12-03 14:02
I've thought about compiler/linker separation too a few times. Particularly when doing the D plugins where the linker has no hard association with the toolsets. I also wanted to play with ld.gold a few times, which would be nice to support.

**Comment by starkos** [comment] 2015-12-03 15:05
I've created PR #353 to roll back the changes. If doesn't cause too much breakage, would it be possible to get that merged? 

I can make some suggestions on working around the gap (override `gcc.getlinks()`, move link flags to `linkoptions()`) if it helps.

I believe that I can make some time available here soon, and I can put this and Tom's `<TargetMachine>` issues at the top of my list.

**Comment by samsinsane** [comment] 2016-02-24 01:22
This issues was resolved in PR #423.

**Closed by samsinsane** 2016-02-24 01:22 UTC

**Comment by gpakosz** [comment] 2016-07-22 08:06
This issue is marked as resolved but I'm facing the problem with `premake5` version `5.0.0-alpha9` on Mac OS X El Capitan version `10.11.5 (15F34)`.

```
$ clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Should I open another issue?

**Comment by starkos** [comment] 2016-07-22 11:14
I believe this was fixed after alpha9 was released. Is it still a problem on the latest master branch?

**Comment by mlabbe** [comment] 2016-08-05 17:28
This appears to be a problem for me, too.  I'm using 5.0.0-alpha9 on macosx with 
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0

**Comment by starkos** [comment] 2016-08-05 18:24
I believe this was fixed after alpha9 was released. Is it still a problem on the latest master branch?

**Comment by mlabbe** [comment] 2016-08-05 18:38
Since I posted that, I can confirm it's been fixed on the latest.  I just built from github's master.

**Comment by starkos** [comment] 2016-08-05 19:00
Great, thanks!
