### ISSUE TITLE
Premake script not embedding include directories within static libraries

### ISSUE THREAD

**Issue by CybernetHacker14** [premake/premake-core#1575] opened 2021-01-08 15:14 UTC
**What seems to be the problem?**
System:- Windows 10
IDE:- Visual Studio 2019 Community
There are four sets of premake files - the first is the workspace file, second is a static library, third is another static library, which links to the second static library, and fourth is the console application which links to the third static library.

I get a compiler error `C1083` when I build the application. The error fires from the end console application, statin `Cannot open include file : <filename.h>: No such file or directory in Visual Studio.

**What did you expect to happen?**
The project should compile without any errors. All intended definitions should be properly found by the compiler within the supplied static libraries.

**What have you tried so far?**
I tried changing and adding more unnecessary include directories to the console application.
I also followed this [link](https://stackoverflow.com/questions/32382431/premake-directive-to-embed-a-static-library-into-a-static-library), and added the extension script to my project, but it doesn't work.

**How can we reproduce this?**
1. Clone this commit - https://github.com/CybernetHacker14/Sentinel-Engine/pull/19/commits/718a85fa2067408dad7e5212faeaa424f84db5b8
2. Go to the `Scripts` folder in the outermost directory, where the workspace premake script resides.
3. Execute `Windows-premake-GenerateProject.bat` file.
4. Open the generated Visual Studio solution folder.
5. Build the application.

**What version of Premake are you using?**
premake5 (Premake Build Script Generator) 5.0.0-alpha14

**Comment by samsinsane** [comment] 2021-01-08 23:06
I'm going to close this off as a duplicate of #627 - they're not the exact same (that one is for `links`, this one is for `includedirs`) but they're the fundamentally the same problem.

**Closed by samsinsane** 2021-01-08 23:06 UTC
Labels: bug
