### ISSUE TITLE
Erroneous project config generation with Premake 5

### ISSUE THREAD

**Issue by SE2Dev** [premake/premake-core#877] opened 2017-08-27 16:23 UTC
Premake 5 (Alpha 12) appears to be generating a separate project level configuration for each configuration, platform combo, whereas Premake 4, GENie, CMake, and most manually managed Visual Studio solutions / projects do not do this. Premake 4 does appear to produce the expected results.

Furthermore, at the bottom of the [Configurations and Platforms](https://github.com/premake/premake-core/wiki/Configurations-and-Platforms) wiki page, it is stated that `It is important to note that projects can't add new configurations to the workspace. They can only remove support for existing workspace configurations, or map them to a different project configuration.`. In Premake 5, however, these do appear to be loaded internally per project, and, as a result, will end up showing up in Visual Studio's project specific configuration list (However they go completely unused when generating files for gmake), how can the behavior for this be standardized.

I have listed below the expected (Premake 4), and current (Premake 5) results from nearly identical project setups, as well as included an archive of both premake*.lua scripts, etc. required to reproduce the same results.

With Premake 4:
![image](https://user-images.githubusercontent.com/5873790/29751569-44a0d126-8b1d-11e7-8012-3225fb64000f.png)

With Premake 5:
![image](https://user-images.githubusercontent.com/5873790/29751579-69d2e510-8b1d-11e7-91a5-3f5412b261e7.png)

[premake-test.zip](https://github.com/premake/premake-core/files/1254529/premake-test.zip)

Edit: It appears that these extra configurations only appear to be generated for non-default platforms (essentially anything other than x32 and x64).

**Comment by starkos** [comment] 2017-08-28 19:08
This is by design. Visual Studio requires that all configurations listed in the solution also be listed in the projects. You can try this yourself by manually creating project files with missing configurations. As soon as you make a change and save, VS will add them.

**Comment by SE2Dev** [comment] 2017-08-28 19:26
But why generate a separate project level configuration for every config / platform combo?

**Comment by starkos** [comment] 2017-08-28 19:40
Because that's how VS does it. Again, you can verify this by manually creating projects as you described above, and then making a change to one and saving it.

Premake's ability to generate deterministic project files that minimize the number of deltas between changes is an important feature to to some organizations; enough so that they have spent a lot of time and effort to identify and fix issues like this. If that use case isn't important to you that might seem silly, but that's how community-built software goes.

I'm going to close this as "by design", but feel free to continue asking questions here.

**Closed by starkos** 2017-08-28 19:40 UTC

**Comment by SE2Dev** [comment] 2017-08-28 20:34
I see now that Visual Studio doesn't actually allow for custom project platforms (although it does for solutions), which I seem to have never noticed, and that this simply allows that behavior to be emulated.
