### ISSUE TITLE
Linking to a static library project doesn't link its dependencies.

### ISSUE THREAD

**Issue by lufsc** [premake/premake-core#1489] opened 2020-07-21 18:10 UTC
**What seems to be the problem?**
When a project links a static library project, only the target of the linked project gets linked. As unix static libraries (contrary to windows .libs) do not contain their dependencies, linking fails.

**What did you expect to happen?**
I expected the makefile to link the static library of the project and then also link the dependencies of that project.

**What have you tried so far?**
I tried to compile the project using the `gmake` and `gmake2` generators, but both of them don't work as expected. The build succeeds, when I enter all dependencies explicitly to all projects.

**How can we reproduce this?**
Create a new workspace containing two static libs and one executable. The second lib should link to the first lib and the executable should link to the second lib. Building the project on linux using `gmake` or `gmake2` results in symbols not being found in the second library (as the first one doesn't get linked). The project builds using `vs2019`.

**What version of Premake are you using?**
`premake5 (Premake Build Script Generator) 5.0.0-dev` (current version of `premake-git` in the arch user repository). The same behaviour is seen from a locally built version.

**Anything else we should know?**
I'm currently diving into the premake5 source code to see if I can fix the problem.

**Comment by samsinsane** [comment] 2020-07-22 01:10
Closing as duplicate of #627.

**Closed by samsinsane** 2020-07-22 01:10 UTC
Labels: bug
