### ISSUE TITLE
'links' static linking not generating a full path and the correct command line arguments in the .make file

### ISSUE THREAD

**Issue by IstuntmanI** [premake/premake-core#900] opened 2017-09-29 14:32 UTC
Originally posted here: https://github.com/premake/premake-core/pull/401#issuecomment-332294842 (you can read the replies in that pull request for some additional informations):

I have a problem when linking static libraries, I guess that it is pretty much related to this pull request, so I won't create an issue for now:
```lua
links { "lib/mysql6.1.10/linux/libmysqlclient.a:static", "lib/mysql6.1.10/linux/libmysqlcppconn-static.a:static" }
```
it outputs this line to the `.make` file:
```cmake
LIBS += -Wl,-Bstatic -llibmysqlclient.a -llibmysqlcppconn-static.a -Wl,-Bdynamic -lrt
```
and it gives me these errors when it comes to the linking stage:
```
/usr/bin/ld: cannot find -llibmysqlclient.a
/usr/bin/ld: cannot find -llibmysqlcppconn-static.a
```

To fix this I need to change the `.make` file:
1. I need to specify the full path.
2. I need to remove the `-l` part before the path

so this works just fine:
```cmake
LIBS += -Wl,-Bstatic lib/mysql6.1.10/linux/libmysqlclient.a lib/mysql6.1.10/linux/libmysqlcppconn-static.a -Wl,-Bdynamic -lrt
```
(I only use these two libraries, so I don't know if this change would break anything)
Is there any way to fix this by changing something in the `links` line from the `.lua` Premake file and I'm doing something wrong, or it is actually a bug ?

**Comment by tdesveauxPKFX** [comment] 2018-04-18 20:12
Not a bug.

When `-l` is given, linker will look for the lib by formatting himself the library name with `lib` and `.a`.

For example, to link a static library `libSuperLib.a` located in `./libs/linux/x32` you should add this in your lua configuration.

```lua
libdirs { "./lib/linux/x32" }
links { "SuperLib" }
```

which will result in a command line with this: `-L./lib/linux/x32 -lSuperLib`.
The linker will then search for SuperLib in paths provided through `-L` option then the `LD_PATH` path environment variable.
For each path, ld default behavior is to look for `libSuperLib.so` then `libSuperLib.a` then go to the next path and do the same.
When you use `links { "SuperLib:static" }`, the `-Wl,-Bstatic` will make ld only look for file with a `.a` extension.

If you what ld does, you can use the `-Wl,--verbose` option for gcc or directly `--verbose` for ld and it will print the step it takes to find the inputted library.

I am closing this, but feel free to open again if necessary.

**Closed by tdesveauxPKFX** 2018-04-18 20:12 UTC
Labels: bug, gmake

**Comment by IstuntmanI** [comment] 2018-04-30 00:42
Thanks for the explanations ! Changing
```links { "lib/mysql6.1.10/linux/libmysqlclient.a:static", "lib/mysql6.1.10/linux/libmysqlcppconn-static.a:static" }```
to
```links { "mysqlclient:static", "mysqlcppconn-static:static" }```
worked flawless.
