### ISSUE TITLE
gmake(2) solution not building on debug configuration

### ISSUE THREAD

**Issue by iFuSiiOnzZ** [premake/premake-core#2020] opened 2023-01-14 16:54 UTC
**What did you expect to happen?**
Have an executable running with debug configuration.

**What have you tried so far?**
I have tried changing configuration filters, file includes, directory structure, different operating systems (Windows [gcc/clang], Linux [gcc/clang]), etc.

**How can we reproduce this?**
[Download link to a test bench](https://drive.google.com/file/d/10j5OeYWc1MDqLUoK8pJcQwjd9UKjiuzD/view?usp=sharing). Generate gmake solution, "premake5 gmake2" and afterwords go the "premake-build" directory and call "make". [Windows GCC/clang compiler](https://winlibs.com/)

**What version of Premake are you using?**
premake5 (Premake Build Script Generator) 5.0.0-beta2

**Anything else we should know?**
On Windows when GCC toolset is used, premake sets the compiler to default one, CC and CXX, which are not defined on Windows. It would be nice to specify gcc and g++ instead.

**Build output**
```
premake5.exe gmake2
Building configurations...
Running action 'gmake2'...
Generated premake-build/Makefile...
Generated premake-build/framework.make...
Generated premake-build/sandbox.make...
Done (25ms).

make CC=gcc config=debug -C .\premake-build\
make: Entering directory 'D:/Projects/aurora/premake-build'
"==== Building framework (debug) ===="
Creating bin
Linking framework
"==== Building sandbox (debug) ===="
Linking sandbox
gcc: fatal error: no input files
compilation terminated.
make[1]: *** [sandbox.make:132: bin/sandboxd.exe] Error 1
make: *** [Makefile:42: sandbox] Error 2
make: Leaving directory 'D:/Projects/aurora/premake-build'

make CC=gcc config=release -C .\premake-build\
make: Entering directory 'D:/Projects/aurora/premake-build'
"==== Building framework (release) ===="
Creating obj/Release/windows/Release/framework
"application.c"
Linking framework
"==== Building sandbox (release) ===="
Creating obj/Release/windows/Release/sandbox
"main.c"
Linking sandbox
make: Leaving directory 'D:/Projects/aurora/premake-build'
```

**Comment by nickclark2016** [comment] 2023-01-14 16:56
This should be resolved by #1932 when it gets merged.

**Comment by iFuSiiOnzZ** [comment] 2023-01-14 18:43
But that only affects tools set not the solution in general. I tried to generate the ninja solution and it has the same problem, it doesn't build on debug. It doesn't generate well the solution, missing includes in this case.

Debug
```
# project build file
# generated with premake ninja

ninja_required_version = 1.6

# core rules for Debug
rule cc
  command = gcc -g -DDEBUG -MMD -MF $out.d -c -o $out $in
  description = cc $out
  depfile = $out.d
  deps = gcc

rule cxx
  command = g++ -g -MD -MP -g -DDEBUG -MMD -MF $out.d -c -o $out $in
  description = cxx $out
  depfile = $out.d
  deps = gcc

rule ar
  command = ar rcs $out $in
  description = ar $out

rule link
  command = gcc -o $out $in
  description = link $out

rule custom_command
  command = $CUSTOM_COMMAND
  description = $CUSTOM_DESCRIPTION

# build files
build obj/Debug/windows/Debug/sandbox/main.o: cc ../sandbox/source/main.c

# link executable
build bin/sandboxd.exe: link obj/Debug/windows/Debug/sandbox/main.o

build sandbox_Debug: phony bin/sandboxd.exe
```

Release
```
# project build file
# generated with premake ninja

ninja_required_version = 1.6

# core rules for Release
rule cc
  command = gcc -O2 -Wall -Wextra -DNDEBUG -I../sandbox/includes -isystem ../framework/includes -MMD -MF $out.d -c -o $out $in
  description = cc $out
  depfile = $out.d
  deps = gcc

rule cxx
  command = g++ -O2 -Wall -Wextra -MD -MP -O2 -Wall -Wextra -DNDEBUG -I../sandbox/includes -isystem ../framework/includes -MMD -MF $out.d -c -o $out $in
  description = cxx $out
  depfile = $out.d
  deps = gcc

rule ar
  command = ar rcs $out $in
  description = ar $out

rule link
  command = gcc -o $out $in -s
  description = link $out

rule custom_command
  command = $CUSTOM_COMMAND
  description = $CUSTOM_DESCRIPTION

# build files
build obj/Release/windows/Release/sandbox/main.o: cc ../sandbox/source/main.c || framework_Release

# link executable
build bin/sandbox.exe: link obj/Release/windows/Release/sandbox/main.o bin/framework.lib

build sandbox_Release: phony bin/sandbox.exe
```

**Comment by nickclark2016** [comment] 2023-01-14 18:51
Ninja is not an exporter supported by the core repository.

**Comment by iFuSiiOnzZ** [comment] 2023-01-14 19:11
Installed VS2022 build tools and the same problem, debug configuration doesn't build :(

**Comment by Jarod42** [comment] 2023-01-14 19:19
Have you try to reset filter before `group`:

```
filter { 'configurations:Release' }
    runtime 'Release'
    warnings 'Extra'
filter {}

group ('Engine')
    include ('framework')
```

**Comment by iFuSiiOnzZ** [comment] 2023-01-14 19:37
Doesn't work reseting the filter.

**Comment by Jarod42** [comment] 2023-01-15 10:29
You have to reset filter in the 3 premake5.lua files.
I succeeded to compile with visual your samples with those fixes (not using gcc as it is not valid, so ignored by vs* action).
(I didn't test other generators, gmake[2] can have the toolset issue. but others should work)

**Comment by iFuSiiOnzZ** [comment] 2023-01-15 12:09
Resetting the filters on the 3 premake files worked. Thank you! :)

**Comment by nickclark2016** [comment] 2023-01-24 12:41
Closing as working as intended.

**Closed by nickclark2016** 2023-01-24 12:41 UTC
Labels: bug
