### ISSUE TITLE
tmainCRTStartup

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#68] opened 2015-05-15 01:56 UTC
What's the go with emitting this `EntryPointSymbol` field into VS projects.
```
LIBCMT.lib(crt0.obj) : error LNK2019: unresolved external symbol main referenced in function __tmainCRTStartup
```
I've been having link troubles with this for years, but I always just go into my project and fix it.
I finally bothered to dig into premake and work out why it's emitting it. I see that unless the `WinMain` flag is defined, it is written.
Do we think this is right?
Surely if kind is WindowedApp, and os is windows, then this should be the default?
It never occurred to me that I would have to set WinMain flag in addition to WindowedApp, and I've just quietly put up with this for years... even though the solution was super obvious.

Opinions?

**Comment by tvandijck** [comment] 2015-05-15 02:09
we're doing the same: 
project 'Heroes'
    targetname 'HeroesOfTheStorm'
    language 'c++'
    kind 'WindowedApp'
    flags{ 'Unicode', 'WinMain' }

For a WindowedApp on windows it would be preferred if that was simply the default. More importantly, that flag is ignored on any other platform anyway, so for our mac build that 'WinMain' is entirely useless...

**Comment by TurkeyMan** [comment] 2015-05-15 05:12
Unicode; that's another good one actually. That should surely be default.
It can't be 2015, and people are writing windows apps without the unicode define set.

**Comment by TurkeyMan** [comment] 2015-05-15 05:13
So, what is the point of 'ConsoleApp' vs 'WindowedApp' if not to automate this WinMain flag? Is there any other interesting distinction between the 2 kinds?

**Comment by tvandijck** [comment] 2015-05-15 15:12
> It can't be 2015, and people are writing windows apps without the unicode define set.
I do all the time actually ;) small utilities, etc...

> So, what is the point of 'ConsoleApp' vs 'WindowedApp' if not to automate this WinMain flag?
Well there is more settings in visual studio that control whether to open up a console or not on startup, but yeah, there isn't much different beside that...

**Comment by starkos** [comment] 2015-05-15 17:10
Ha! That flag has been in there since 1.0; I can't believe it took this long for someone to raise this issue. I'm fine with making WinMain the default for WindowedApp builds. The historical explanation is that I wrote Premake to support cross-platform game development, and we needed apps to not display the Console on startup, but to have a consistent entry point across platforms.

The Unicode flag, on the other hand, I think should stay as-is. The intention is to use the toolset's default unless the project author says otherwise.

**Comment by TurkeyMan** [comment] 2015-05-17 01:09
Okay, so you support a patch to remove the WinMain flag? Should it be replaced by an 'entrypoint' api or something for the rare event that someone does want to specify an entrypoint?

I guess I can kinda dig your 'toolset default' argument... but in this case, I kinda feel compelled to break that principle. For the last 10 years or so, I operate under the assumption that windows programs without UNICODE are technically broken (I've done lots of localisation though). Other operating systems support unicode, but windows is ANSI by default, and that's proven to be really bad in my experience, since many programmers are American, and don't even know what Unicode is.
Generating 'not-broken' projects by default is a nice little nudge to programmers that don't otherwise care about people in other countries to take a moment to think about what they're doing.

I accept it's not really the place to make an ideological statement... but it's not really ideological, it's mostly practical. Without 'Unicode', other platforms will work, windows will be broken.
In my experience, it's usually a bug just waiting to be logged in most cases.

**Comment by TurkeyMan** [comment] 2015-05-17 01:13
> > It can't be 2015, and people are writing windows apps without the unicode define set.

> I do all the time actually ;) small utilities, etc...

You're a bad man! :P

**Comment by starkos** [comment] 2015-05-18 16:55
> Okay, so you support a patch to remove the WinMain flag? Should it be replaced by an 'entrypoint' api or something for the rare event that someone does want to specify an entry point?

We should be careful about how we handle this, because that flag has been there since the beginning and people may have a lot of projects using it.

I think, for now, the flag should stay in place. We can show a message if people use it with a WindowedApp build to let them know it is no longer needed.

And yes, we absolutely need a new way to have a main() entry point without having the Console pop up. I don't recall which VS flags are involved off the top of my head though; perhaps we have a "NoConsole" flag or something? Thoughts?

Oh, and we'll want a prominent mention of the error and how to resolve it for all the people who will suddenly be getting WinMain linker warnings.

**Comment by starkos** [comment] 2015-05-18 16:57
> I guess I can dig your 'toolset default' argument... but in this case, I kinda feel compelled to break that principle. For the last 10 years or so, I operate under the assumption that windows programs without UNICODE are technically broken

Fair enough, but I still think it is more intuitive to match the toolset defaults, even if they *are* broken :)

**Comment by TurkeyMan** [comment] 2015-05-19 11:39
> I think, for now, the flag should stay in place. We can show a message if people use it with a WindowedApp build to let them know it is no longer needed.

Not a normal deprecated message?

> And yes, we absolutely need a new way to have a main() entry point without having the Console pop up. I don't recall which VS flags are involved off the top of my head though; perhaps we have a "NoConsole" flag or something? Thoughts?

I'm not sure I understand... isn't that just what `WindowedApp` as opposed to `ConsoleApp` means? Why the need for a new flag?
Are you saying that `WindowedApp` strictly implies WinMain? I would suggest a new API to set the entrypoint, then `kind "WindowedApp"` + `entrypoint "main"` would do this, no?

> Oh, and we'll want a prominent mention of the error and how to resolve it for all the people who will suddenly be getting WinMain linker warnings.

Do you mean for people who currently use `WindowedApp`, but don't use `WinMain`?

**Comment by starkos** [comment] 2015-05-19 14:56
> Not a normal deprecated message?

Sorry yes, a deprecation message.

> Are you saying that WindowedApp strictly implies WinMain?

Isn't that the result of the change you're proposing? Did I misunderstand?

> then kind "WindowedApp" + entrypoint "main" would do this, no?

I think that's good, and more flexible than what we have currently.

**Comment by TurkeyMan** [comment] 2015-05-20 01:47
What I was proposing is that WinMain is simply the default entrypoint for `kind "WindowedApp"` on windows. We then add an `entrypoint` api so users can change the entrypoint as they like; which makes the old default functionality available.

If you're on board, I'll do this soon.

**Comment by starkos** [comment] 2015-05-20 15:47
Yes, sounds good.

> Do you mean for people who currently use WindowedApp, but don't use WinMain?

Yes exactly, these projects are going to suddenly start having link errors on WinMain. There is no good way I can think of to warn or otherwise point people to the cause and fix.

**Comment by TurkeyMan** [comment] 2015-05-21 04:30
Yeah, I can't think of a good solution to this. Just document it in the premake5 release changes. Anyone on premake5 now understands they are following an alpha release.

**Comment by Sairony** [comment] 2015-07-03 13:32
We had a bug where our OpenGL program was crashing after main, removing mainCRTStartup as the startup point solved it. So don't even know if mainCRTStartup actually is a legit starting point under all circumstances.

**Comment by samsinsane** [comment] 2015-10-09 08:18
Closing this as it looks like the suggested API, `entrypoint`, has been created and resolves the original issue.

**Closed by samsinsane** 2015-10-09 08:18 UTC
