### ISSUE TITLE
path.getrelative where common is root return absolute path

### ISSUE THREAD

**Issue by tdesveauxPKFX** [premake/premake-core#982] opened 2017-12-20 14:33 UTC
`path.getrelative("C:/Code/Premake4", "C:/Binaries/obj/debug")`
return
`C:/Binaries/obj/debug`
where it would make more sense to me that it return
`../../Binaries/obj/debug`

There is this comment in path_getrelative.c
```
/* if I end up with just the root of the filesystem, either a single
 * slash (/) or a drive letter (c:) then return the absolute path. */
```
and the commit (b3216cbcf87) refers to issue #213 which probably come from a previous bug tracking.

Are you interested in a pull request that would make getrelative work as I stated before?

**Comment by starkos** [comment] 2017-12-20 18:44
No, the current behavior is correct. The issue it is addressing is a use case like this:

```lua
includedirs { '/usr/local/include' }
```

If you try to turn that into a relative path, it will break when the project is moved elsewhere and placed at a different folder depth.

I'm going go ahead and close this as "by design", but feel free to reopen if you'd like to discuss it further.

**Closed by starkos** 2017-12-20 18:44 UTC
