### ISSUE TITLE
Issue generating project files

### ISSUE THREAD

**Issue by DCubix** [premake/premake-core#1781] opened 2021-12-23 18:00 UTC
Hello, I'm trying to generate the project files for VS2022, but I'm getting the following error:
![image](https://user-images.githubusercontent.com/5081992/147276749-b585feb2-28e6-440d-a280-6c12fb624040.png)

This is my build script
```lua
workspace "Engine"
    kind "ConsoleApp"
    language "C++"
    cppdialect "C++2a"
    
    files { "src/**.h", "src/**.cpp", "src/**.hpp" }
    
    configurations { "Debug", "Release" }
    platforms { "x64" }

    targetdir "bin/%{cfg.buildcfg}-%{cfg.platform}"

    links { "SDL2", "lua53", "png" }
    
    filter "platforms:x64"
        system "Windows"
        architecture "x64"
        
    filter "configurations:Debug"
        defines { "DEBUG" }
        symbols "On"
        
    filter "configurations:Release"
        optimize "On"
```

I'm using `premake5 (Premake Build Script Generator) 5.0.0-beta1`

**Comment by nickclark2016** [comment] 2021-12-23 22:04
Can you try using "C++20" instead of "C++2a"?  Looking at the code, 2a is not supported for MSVC.  If that doesn't work, I'll dig into it deeper after the holiday!

**Comment by DCubix** [comment] 2021-12-24 14:11
> Can you try using "C++20" instead of "C++2a"? Looking at the code, 2a is not supported for MSVC. If that doesn't work, I'll dig into it deeper after the holiday!

Yeah I tried with C++20 and got the same message

**Comment by nickclark2016** [comment] 2021-12-24 14:21
Hmm, I'll take a look in a few days.  Is this just VS2022, or does this issue affect 2019 as well?

**Comment by DCubix** [comment] 2021-12-24 18:17
@nickclark2016 happens with every version

**Comment by nickclark2016** [comment] 2022-01-12 18:48
I'm not able to reproduce this.  Could you try redownloading premake and verifying if you still have the issue?

**Comment by samsinsane** [comment] 2022-01-16 11:26
@DCubix You're only specifying a `workspace` but not any `project`s.

@nickclark2016 I guess we should emit a warning instead of error out like this? It's a strange situation to have, but it is not very clear at all what the problem is, especially for someone new to Premake.

**Comment by nickclark2016** [comment] 2022-08-22 00:47
Looks like that was indeed the problem. Closing issue. Please comment if you still have the issue and I'll reopen.

**Closed by nickclark2016** 2022-08-22 00:47 UTC
Labels: support-request
