### ISSUE TITLE
Configuration tokens does not work in postcommands

### ISSUE THREAD

**Issue by Mumsfilibaba** [premake/premake-core#1391] opened 2020-01-23 10:37 UTC
When using postbuildcommand, the tokens that uses "cfg" does not work. I tried for the example on the custom build commands page (https://github.com/premake/premake-core/wiki/Custom-Build-Commands)

`"postbuildcommands { "{COPY} %{cfg.objdir}/output.map %{cfg.targetdir}" }"`

This generates the following error 
`"Error: [string "return cfg.objdir"]:1: attempt to index a nil value (global 'cfg') in token: cfg.objdir"`

This happens when using trying to generate a xcode4 project.

I'm trying to copy my resources folder to the compiled executable's folder. Does anyone know any other way of achieving this? Because this should work right, since the i'm using the tokens when I specify the targetdir, like this:
`outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"`
`targetdir 	("Build/bin/" .. outputdir .. "/%{prj.name}")`

If I copy the exact same tokens they does not work in the postbuildcommad, in other words this does not work:

`"postbuildcommands { "{COPY} res/shaders/vertex.glsl/ Build/bin/%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}/%{prj.name}"}"`

**Comment by samsinsane** [comment] 2020-01-23 11:36
This appears to be a duplicate of #1013

**Closed by samsinsane** 2020-01-23 11:36 UTC
Labels: bug
