### ISSUE TITLE
test suite.matchfiles_OnDottedFile fails due to missed .gitignore

### ISSUE THREAD

**Issue by van-de-bugger** [premake/premake-core#640] opened 2016-11-28 20:28 UTC
$ wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-src.zip
    $ unzip premake-5.0.0-alpha10-src.zip
    $ cd premake-5.0.0-alpha10
    $ ( cd build/gmake.unix/ && make )
    $ bin/release/premake5 test
    Running action 'test'...
    base_os.matchfiles_OnDottedFile: .../premake-5.0.0-alpha10/tests/base/test_os.lua:109: expected true but was false
    1432 tests passed, 1 failed in 1.43 seconds

Problem: Missed file `.gitignore`.

**Comment by tvandijck** [comment] 2016-11-28 20:54
Duplicate of #595 
Fixed in #613

**Closed by tvandijck** 2016-11-28 20:54 UTC
