### ISSUE TITLE
How to generate the iOS FrameWork

### ISSUE THREAD

**Issue by panhaowen** [premake/premake-core#1169] opened 2018-09-16 11:08 UTC
I tried the following, but to no avail
kind "SharedLib"
sharedlibtype "OSXFramework"

**Comment by neo2buha** [comment] 2018-09-29 18:32
I''m afraid this might not work just out of the box 
Could you attach here a pbxproject generated by xcode for references ?
I'll try to look into it and  submit a merge request once i have the project and the time to look into it !

**Comment by samsinsane** [comment] 2018-11-28 14:38
I'm going to close this and assume that the issue was resolved in the above PR. If the issue is still occurring please feel free to reopen the issue.

**Closed by samsinsane** 2018-11-28 14:38 UTC
