### ISSUE TITLE
Windows Premake5 Alpha 13 links including .a file

### ISSUE THREAD

**Issue by EmersonSnow** [premake/premake-core#1222] opened 2019-01-11 02:02 UTC
Hi,

I want to include .a file via links, but it automatically adds the .lib extension. Is it possible to do this, or is a feature needs adding?

Thank you,

All the Best

**Comment by samsinsane** [comment] 2019-01-11 02:34
This seems like a duplicate of #1024. It's possible if you override an internal function (code provided in link) but there isn't an out of the box way to do this, yet.

**Closed by samsinsane** 2019-01-11 02:34 UTC
