### ISSUE TITLE
Can't use includedirs with filters

### ISSUE THREAD

**Issue by crazydef** [premake/premake-core#1478] opened 2020-07-07 09:40 UTC
I have something similar to the following set up in one of my projects:

```
includedirs { ...some common paths... }

filter { "configurations:Debug" }
  includedirs { "somepath/debug" }
filter {"configurations:Release" }
 includedirs { "somepath/release" }
filter {}
```

However, the include paths in the resulting (visual studio 2019) project file contain all paths merged together for both build configurations:

somepath/debug
...some common paths...
somepath/release

Which is not what I would expect, and isn't very helpful.  (Having to use a third party library that puts header files in the build directory isn't very helpful either, but I digress.)

I would have expected the Debug build configuration to contain common paths plus debug specific paths, and the Release configuration to contain the same common paths, and the release specific ones.

I have seen this behaviour with both `filter` and `configuration`, which suggests it's a problem with how includedirs are managed internally.

I'm using Premake version 5.0.0-alpha14.

**Comment by starkos** [comment] 2020-07-09 13:03
I tried to reproduce your issue here with no luck. My script:

```lua
workspace 'MyWorkspace'
    configurations { 'Debug', 'Release' }

project 'MyProject'
    kind 'ConsoleApp'
    files { 'Hello.cpp' }

    includedirs { 'include1' }

    filter { "configurations:Debug" }
        includedirs { 'include_debug' }

    filter {"configurations:Release" }
        includedirs { 'include_release' }
```

My results:

```xml
<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
  <ClCompile>
    <PrecompiledHeader>NotUsing</PrecompiledHeader>
    <WarningLevel>Level3</WarningLevel>
    <AdditionalIncludeDirectories>include1;include_debug;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    <Optimization>Disabled</Optimization>
  </ClCompile>
  <Link>
    <SubSystem>Console</SubSystem>
  </Link>
</ItemDefinitionGroup>
<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
  <ClCompile>
    <PrecompiledHeader>NotUsing</PrecompiledHeader>
    <WarningLevel>Level3</WarningLevel>
    <AdditionalIncludeDirectories>include1;include_release;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    <Optimization>Disabled</Optimization>
  </ClCompile>
  <Link>
    <SubSystem>Console</SubSystem>
  </Link>
</ItemDefinitionGroup>
```

You might want to try creating a simpler version of your project to see if the problem persists. I'm going to go ahead and close this issue as unable to reproduce, but feel free to reopen if you discover more information.

**Closed by starkos** 2020-07-09 13:03 UTC
Labels: bug

**Comment by silvertakana** [comment] 2022-03-02 09:12
I had the same problem. I tried filtering out specific files instead. It filtered fine but when I use `includedirs`, it did not work. So I tested with defines. And it worked, it manage to filter out specific files but did not manage to add the additional include directory that I wanted.
