### ISSUE TITLE
VS2019 project (and solution) marked as skipped.

### ISSUE THREAD

**Issue by CyVlBel** [premake/premake-core#1488] opened 2020-07-19 21:49 UTC
Hi all,
I'm trying to write premake file to generate vs2019 solution.

Problem: generated solution and project marked in VS  as skipped. At the same time, when I'm trying to build it, build is successful.

My project structure: 
```
root
    premake5.lua
    3rd/
        eigen/
            ...
    src/
        /math
            /linalg
                /src
                    *.h, *.cpp
```
My premake file
```Lua
workspace "light-propagator"
    architecture "x64"
    configurations { "Debug", "Release" }


outputdir = "%{cfg.buildcfg}_%{cfg.system}_%{cfg.architecture}"

project "linalg"
    location "src/math/linalg"
    kind "StaticLib"
    language "C++"

    targetdir ("bin/" .. outputdir .. "/%{prj.name}")
    objdir ("bin/obj/" .. outputdir .. "/%{prj.name}")

    includedirs {
        "3rd/eigen"
    }

    files { 
        "src/math/linalg/src/**.cpp",
        "src/math/linalg/src/**.h"
    }

    filter "configurations:Debug"
        defines { "DEBUG" }
        symbols "On"
    
    filter "configurations:Release"
        defines { "NDEBUG" }
        optimize "On"
    
    filter "system:windows"
        cppdialect "C++17"

```

I'm using premake5 (Premake Build Script Generator) 5.0.0-alpha15

**Comment by samsinsane** [comment] 2020-07-20 00:57
It looks like you've included an extra path in your `files` entries - `src/math/linalg` should be `src/linalg` based on your project layout mentioned above.

**Comment by CyVlBel** [comment] 2020-07-20 08:04
> 
> 
> It looks like you've included an extra path in your `files` entries - `src/math/linalg` should be `src/linalg` based on your project layout mentioned above.

It was a typo in issue description, corrected, thank you. The problem still relevant.

**Comment by CyVlBel** [comment] 2020-07-20 14:30
> 
> 
> I've copied your provided Premake script, it all seems to be working fine for me. Where in VS is it marked as skipped?

In the solution explorer
![изображение](https://user-images.githubusercontent.com/43202094/87949337-915af900-caae-11ea-8dd6-23baa4ab6c2f.png)

**Comment by samsinsane** [comment] 2020-07-21 13:04
Interesting, I have never noticed that before - it looks like it's the Git support in VS that adds this. I assume it's marked as ignored because the files aren't being tracked?

**Comment by CyVlBel** [comment] 2020-07-21 14:53
> 
> 
> Interesting, I have never noticed that before - it looks like it's the Git support in VS that adds this. I assume it's marked as ignored because the files aren't being tracked?
I'm sure that files are tracked in the repository. In VS the files are not marked 
![изображение](https://user-images.githubusercontent.com/43202094/88070186-14498580-cb7b-11ea-8681-2b4d95f924ea.png)

**Comment by samsinsane** [comment] 2020-07-22 01:06
Sorry, I meant specifically the `.sln` and `.vcxproj` files, these aren't being tracked, so they're marked as ignored. I don't think there's anything wrong or bugged here, it's just VS telling you the generated files aren't tracked by version control. I'm going to close this issue as this is all working as intended.

**Closed by samsinsane** 2020-07-22 01:06 UTC
Labels: support-request
