### ISSUE TITLE
{copy} command on Windows needs an asterisk

### ISSUE THREAD

**Issue by redorav** [premake/premake-core#1015] opened 2018-03-07 21:14 UTC
~~I don't know if this has been asked before, so apologies if this is a duplicate.~~ I just realized this has been mentioned here https://github.com/premake/premake-core/issues/819. When I first started with premake I added a {copy} command to the postbuildcommands. It all worked fine except for the fact that I needed to add an asterisk at the end of the command to make it work, otherwise the build would fail. Fair enough, I added it and moved on. https://stackoverflow.com/questions/4283312/batch-file-asks-for-file-or-folder

However I've now come back to this since Mac doesn't require the asterisk to do the copy and I find myself doing if _ACTION == "vs2017" to add this asterisk if on Visual Studio. My command looks like this:

"{copy} \"%{cfg.buildtarget.abspath}\" \"../../Binaries/"..ProjectName..".".._ACTION..".%{cfg.buildcfg:lower()}".."%{cfg.buildtarget.extension}\"*"

Notice the asterisk at the end. I would guess this is something for premake to handle internally, as the {copy} already gets handled. I'm not sure if the asterisk is the proper way of doing it for every case, just one that happens to work in my scenario. Any thoughts?

**Comment by marvincountryman** [comment] 2018-03-21 17:48
Adding an asterisk is working for me. I think the cross platform solution is for premake to use the COPY command instead for this situation.

**Comment by redorav** [comment] 2018-03-21 18:05
I *think* the problem with copy is it doesn't create the folder structure for you or help you in any way, so it's easy for a file copy to fail if you haven't set up everything right. It would probably need more investigation to come up with a better solution.

**Comment by marvincountryman** [comment] 2018-03-21 18:20
From what I found the {COPY} token is parsed as XCOPY.  If the file does not exist XCOPY will prompt you with ```{filename} specify a file name or directory name on the target
(F = file, D = directory)?``` and unfortunately you cannot tell XCOPY to prefer a file with a flag as far as I can tell.

**Comment by starkos** [comment] 2018-03-22 19:01
One complication: at the time the Premake script is run, there may not be any way to tell if we're going to be copying a file or a directory. Do we maybe need to have separate `COPYFILE` and `COPYDIR` tokens instead?

**Comment by redorav** [comment] 2018-03-22 21:28
Perhaps that is the better approach, we can probably add flags and options that don't apply to one but do apply to the other. One unfortunate thing I've figured out is that the asterisk at the end of the file (the proposed solution of this bug) doesn't allow you to have a longer or shorter extension... i.e. doing

> xcopy filename.extension new_filename.new_extension*

will fail. It may not be a frequent scenario, but it's entirely possible. Another thing I've figured out is that xcopy will not prompt if the file already exists. I wonder if we can do something like:

> mkdir dir_to_new_file // create folder structure
> cd . > dir_to_new_file\new_filename.new_extension // create empty file
> xcopy filename.extension dir_to_new_file\new_filename.new_extension // actually do the copy

It's mildly annoying how difficult they've made it to make xcopy simply work. The other suggestion I saw before is to pipe F into the command by doing echo | F, but apparently it's not locale-independent (as in German for instance uses, ironically, D for files) The other thing I investigated is robocopy, but aside from the fact that it's not available in XP (although I don't know how much user base that would be) it looks like it's even more awkward to copy single files.

On other other hand, xcopy can easily be told about directories by just appending a \ at the end of the directory name and just works. Does this seem like a reasonable solution?

**Comment by samsinsane** [comment] 2018-03-23 12:38
I'm going to say that this, #1022 and #819 are all the same thing. To be frank, I detest the `{COPY}` token, I attempted to get it to at least detect the source type and provide the `/E` switch when it was a folder - can't recall the exact bug, something to do with empty folders being generated when it was a file I think. I think some of the issues stem from how much `cp` does by default compared to `xcopy`, such as copy files and folders without prompting.

One of the biggest issues is this line: https://github.com/premake/premake-core/blob/3e204522ec191116a66edfc276fa2fc75b372847/src/base/os.lua#L587

If you have `{COPY} src dst`, `v` is `src dst`. That's just nonsense! And, in the event you specify `/` at the end to indicate that it's a path, it's going to throw it out anyway! There's no way to specify options on Windows, `/F` is translated to `\F`, I imagine on *nix `-F` would be fine. Unfortunately, once you allow options you immediately need to know the underlying command, and then you're going to use filters anyway!

Perhaps, tokens need arguments? `{COPY -EmptyFolders} src/path dst` `{COPY -FileDestination} src/name.ext dst/new.new` `{COPY -OverrideNew} src/* dst` - this would give more flexibility to copying (and other commands! `mkdir` without `-p` for example) and gives power to the users. I appreciate the pre-set flags, but some of them make the token useless for a certain situation.

**Comment by redorav** [comment] 2020-10-05 09:43
@samsinsane Does 802435304fc2957232b4e9f0042bd6516f9d7a25 essentially fix this issue?

**Comment by samsinsane** [comment] 2020-10-05 09:53
More or less? I didn't really look for existing issues because `{COPY}` hasn't changed, I guess once we deprecate it we can start closing issues off. If you're satisfied with using the new tokens instead, then I'm happy for this to be closed off since we will be moving to deprecate `{COPY}`, I just want to make sure that `{COPYDIR}` works the same before doing this.

**Comment by redorav** [comment] 2020-10-05 10:03
That's a fair point, I'll give the new tokens a spin and if everything works the way it used to I'll go ahead and close it off

**Comment by samsinsane** [comment] 2021-08-07 08:42
I'm going to close this off assuming that `{COPYDIR}` works as intended.

**Closed by samsinsane** 2021-08-07 08:42 UTC
