### ISSUE TITLE
Premake build fails on Xcode 14.3

### ISSUE THREAD

**Issue by tempura-sukiyaki** [premake/premake-core#2092] opened 2023-05-30 11:32 UTC
**What seems to be the problem?**

When trying to build Premake with Xcode Command Line Tools 14.3 (14E222b), the build of contrib/libzip fails with the following error

```
../../contrib/libzip/mkstemp.c:76:8: error: call to undeclared function 'getpid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```

On Xcode Command Line Tools 14.2 (14C18), the build succeeds.

**What did you expect to happen?**

The build should also succeed with Xcode Command Line Tools 14.3 (14E222b).

**What have you tried so far?**

I added the following line to [contrib/libzip/premake5.lua](https://github.com/premake/premake-core/blob/master/contrib/libzip/premake5.lua#L23) and the build succeeded.

1.

```lua
	filter "system:macosx"
		defines { "HAVE_SSIZE_T_LIBZIP" }
		forceincludes { "unistd.h" }
 ```

2.

```lua
	filter "system:macosx"
		defines { "HAVE_SSIZE_T_LIBZIP" }
		disablewarnings { "implicit-function-declaration" }
 ```

I'm just not sure which of these is the better method (or maybe both are bad).

I thought the following might be the best description.

3.

```lua
	filter "system:macosx"
		defines { "HAVE_SSIZE_T_LIBZIP", "HAVE_UNISTD_H" }
		forceincludes { "include/zlib.h" }
 ```

**How can we reproduce this?**

- [ ] Visual Studio 2022 (vs2022)
- [ ] Visual Studio 2019 (vs2019)
- [ ] Visual Studio 2017 (vs2017)
- [ ] Visual Studio 2015 (vs2015)
- [ ] Visual Studio 2012 (vs2012)
- [ ] Visual Studio 2010 (vs2010)
- [ ] Visual Studio 2008 (vs2008)
- [ ] Visual Studio 2005 (vs2005)
- [ ] GNU Makefile (gmake)
- [ ] GNU Makefile 2 (gmake2)
- [ ] XCode (xcode)
- [ ] Codelite
- [x] Other (Please list below)

1. Switch Xcode Command Line Tools to 14.3 (14E222b).

2. Build Premake with `make -f Boostrap.mak osx`.

**What version of Premake are you using?**

Latest master branch.
https://github.com/premake/premake-core/commit/d691c56b512d81e95e5da5653b9558921062ee56

**Anything else we should know?**

Nothing in particular.

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

Translated with www.DeepL.com/Translator (free version)

**Comment by Jarod42** [comment] 2023-06-01 12:15
Contrib are external projects, try to check if they have issue on their repo too.
(I would like those dependencies were managed differently (as submodule or fetching their content, or ...))

**Comment by tempura-sukiyaki** [comment] 2023-06-02 02:32
Thanks for your comment.

The latest official version of libzip builds successfully with Xcode Command Line Tools 14.3.
https://github.com/nih-at/libzip

It is difficult to compare the libzip in contrib/libzip as it has not been updated in about 10 years.
For example, there is an error in the file [contrib/libzip/mkstemp.c](https://github.com/premake/premake-core/blob/master/contrib/libzip/mkstemp.c), but this file does not exist in the latest libzip.

Also, libzip uses CMake as its build system (and it seems to have done so 10 years ago according to the logs), but premake-core uses the Premake script [contrib/libzip/premake5.lua](https://github.com/premake/premake-core/blob/master/contrib/libzip/premake5.lua).

I think [contrib/libzip/premake5.lua](https://github.com/premake/premake-core/blob/master/contrib/libzip/premake5.lua) is a file created by premake-core itself, so I think that file should be modified.

Translated with www.DeepL.com/Translator (free version)

**Comment by chenrui333** [comment] 2023-06-05 16:13
I am seeing the similar issue in [my homebrew build](https://github.com/Homebrew/homebrew-core/pull/132325) (with 5.0.0-beta2) as well

I think it would be good to also have an option to use the system provided libzip (some xcode failures have already been [resolved by libzip side](https://github.com/nih-at/libzip/commit/70629b26c0ad0a709c444921574f49454850dea0))

**Comment by wraitii** [comment] 2023-08-09 13:11
We are encountering the same problem within 0 A.D., see https://code.wildfiregames.com/D5093

The patch there is to suppress the error.

**Comment by nickclark2016** [comment] 2023-08-09 14:24
Initially, we can drop in a force include for `zlib.h` as suggestion 3 stated.  That should fix it until we can update the distribution.

**Comment by nickclark2016** [comment] 2023-08-09 14:39
I don't have a mac machine to test on, but assuming this passes the build steps, I think we can go ahead and merge this.  @wraitii @tempura-sukiyaki would either of you be willing to verify the build works on your machines?

**Comment by wraitii** [comment] 2023-08-09 15:35
> I don't have a mac machine to test on, but assuming this passes the build steps, I think we can go ahead and merge this. @wraitii @tempura-sukiyaki would either of you be willing to verify the build works on your machines?

I should be able to give this a try tomorrow, haven't compiled Premake outside of 0 A.D. but I guess it's straightforward enough

**Comment by nickclark2016** [comment] 2023-08-09 21:53
> > I don't have a mac machine to test on, but assuming this passes the build steps, I think we can go ahead and merge this. @wraitii @tempura-sukiyaki would either of you be willing to verify the build works on your machines?
> 
> I should be able to give this a try tomorrow, haven't compiled Premake outside of 0 A.D. but I guess it's straightforward enough

Appreciated. Feel free to ping me directly if you've got questions on the build process.

**Comment by wraitii** [comment] 2023-08-10 12:39
> Appreciated. Feel free to ping me directly if you've got questions on the build process.

Sorry, forgot that I don't have Xcode 14.3 and so I don't actually reproduce the original issue. I can confirm that your PR works for me, but not that it actually fixes the problem.
I've pinged one of our users that did experience the issue, hopefully they'll be able to reproduce.

**Comment by nickclark2016** [comment] 2023-08-10 12:48
When you say the problem, does it still not build, or just in that we've got an outdated build of libzip and should update (for which I completely agree, I just won't have time to do that for a bit).

**Comment by wraitii** [comment] 2023-08-10 14:04
> When you say the problem, does it still not build, or just in that we've got an outdated build of libzip and should update (for which I completely agree, I just won't have time to do that for a bit).

No, I mean it always builds for me, because I'm an earlier version of Xcode on my computer. So the PR doesn't "fix" things. The 'problem' is that it doesn't compile, though yeah it would likely be a good thing to upgrade the lib zip version.

**Comment by nickclark2016** [comment] 2023-08-10 14:07
Sounds good. If your colleague (or someone else here with 14.3) can confirm a build, I'll gladly merge, then put an update to libzip on the backlog.

**Comment by wraitii** [comment] 2023-08-14 12:10
@nickclark2016 Your PR fixes the issue according to one of our users, so I think it's good to go.

**Comment by nickclark2016** [comment] 2023-08-14 12:24
Sounds good. I'll go ahead and get that into the main branch.

**Closed as completed** 2023-08-14 12:26 UTC
Labels: bug
