### ISSUE TITLE
Deployment support vs2005_solution

### ISSUE THREAD

**Issue by youaresoomean** [premake/premake-core#476] opened 2016-04-14 09:03 UTC
Hi,

some VS target support deployment to devices (e.g. android support). Currently there's no way to add (cfg).Deploy0.(arch) to the .sln files.
The following override adds support for it, would be nice to integrate it into the main branch:

```
api.register {
        name = "deploy",
        scope = "project",
        kind = "boolean",
    }

 premake.override(premake.vstudio.sln2005.elements,"projectConfigurationPlatforms", function(oldfn,cfg)
        local elements = oldfn(cfg)
        if cfg.kind ~= premake.UTILITY then
            elements = table.join(elements, {
                 sln2005_deploy0
            })
        end
        return elements
    end)

    function sln2005_deploy0(cfg,context)
        if not context.excluded and context.prjCfg.kind ~= premake.NONE then
            if context.prjCfg.deploy == true then
                p.w('{%s}.%s.Deploy.0 = %s|%s', context.prj.uuid, context.descriptor, context.platform, context.architecture)
            end
        end
    end
```

**Comment by samsinsane** [comment] 2016-04-14 11:33
> some VS target support deployment to devices (e.g. android support). Currently there's no way to add (cfg).Deploy0.(arch) to the .sln files.

The code you provided is exactly how you do that, by design. I think we can probably improve on the way call arrays are overridden, something along the lines of `premake.override(premake.vstudio.sln2005.elements, "projectConfigurationPlatforms", { sln2005_deploy0 })` would be good. What do you think @starkos? All the checks (`if cfg.kind ~= premake.UTILITY then`) can be done within the functions instead, IMO, it makes more sense for the functions to check than the override function.

> would be nice to integrate it into the main branch

I disagree, this is code used by modules. If there was a use case for this in premake-core, it would be a different story, but premake-core shouldn't really contain code in the exporters that only modules utilize. Module developers already need to submit PRs to fix issues in premake-core and doing things like this would only make that more frequent, I actually submitted a PR (#284) so that you could do the above instead of copying ~100 lines from the exporter and adding the contents of `sln2005_deploy0` to it.

**Comment by starkos** [comment] 2016-04-14 23:26
So yes, it would be good to have an official way to add the `.Deploy` line to the solution—we don't want multiple modules to be trying to implement that themselves. But as @samsinsane said, this is a feature that should be turned on and off by the modules when it is appropriate; a user-facing API call doesn't really make sense in that context.

I don't think we've ever encountered this situation before. Is this something that we could trigger automatically for certain architectures, and just expose a list of "deployable" architectures?

**Comment by youaresoomean** [comment] 2016-04-15 06:30
I only came across this when modifying the vsandroid module to output VS2015 compatible android projects. The actual main project is of type .androidproj which i currently just link as an externalproject and set deploy0 via the override above. So it's bound to a certain project type in this case. Not sure about other app types like UWP..

**Comment by samsinsane** [comment] 2016-04-15 06:37
Are you talking about [this](https://github.com/TurkeyMan/premake-android) module? I have an open PR which adds VS2015 support for that project, you can use that. I need to do some work on it to get it into the layout that @TurkeyMan wants, but it should work for you, if there's anything missing let me know. I'm more than happy to get it working for you, I kind of rushed through it for my own project.

**Comment by youaresoomean** [comment] 2016-04-15 07:26
Yes, oh no..i missed the PR..would have saved me a week of work. My modifications are more crude..just to get something working. Will check your PR out and see if it works for our projects.

**Comment by samsinsane** [comment] 2016-04-15 08:32
@youaresoomean feel free to comment on the PR if something doesn't work or if I did something in a really bad way, I'll try to get them sorted out as quickly as I can.

@starkos I don't want to go too off topic, but the VS exporter could do with a bit of redesign with the some of the VS2015 extensions in mind. Android, iOS, WinRT and Linux are all Microsoft extensions and the current exporter doesn't quite support them.

As for the current issue at hand, could Premake-core support the deploy line like:
```lua
function m.deploy0(cfg, context, emit)
  if emit then
    p.w('{%s}.%s.Deploy.0 = %s|%s', context.prj.uuid, context.descriptor, context.platform, context.architecture)
  end
end
```
and then a module would just need to do:
```lua
premake.override(premake.vstudio.sln2005, "deploy0" function (oldfn, cfg, context, emit)
  oldfn(cfg, context, emit or (moduleConditions))
end)
```
I feel like there's a reason this won't work? It does rely on module developers to pass the emit parameter down, very trusting that other modules don't break the chain. Alternatively, there could be a call array that `m.deploy0` calls and if any of the functions return true it emits the tag?

**Comment by starkos** [comment] 2016-04-15 14:31
Could we keep a table of "deployable" platform and/or architecture identifiers? Modules would be free to add new values to the table. Then the function could be written generically. Maybe something like (completely made up, I don't know the actual identifiers):

```lua
m.deployableArchitectures = {
   "Android"
   "iOS"
}

function m.isDeployable(context)
   return (m.deployableArchitectures[context.platform] ~= nil)
end

function m.deploy0(cfg, context, emit)
  if m.isDeployable(context) then
    p.w('{%s}.%s.Deploy.0 = %s|%s', context.prj.uuid, context.descriptor, context.platform, context.architecture)
  end
end
```

…? 

If that works, maybe we'd want an `m.addDeployableArchitecture()`, and maybe that whole idea of "deployable architectures" should be in core rather than in the VS exporter, but something to start with?

**Comment by samsinsane** [comment] 2016-04-16 03:00
There isn't really a generic solution to this unfortunately.

Android and iOS would match on the project extension (`.androidproj` and `.iosproj`), as only the packaging projects do the deployment. While WinRT would match on the system and project kind, or at least this is how I do it, if it's a WinRT system being targeted and the project is a windowed application, then it is deployed.

Both of these approaches are pretty naïve, there might be a situation where a user doesn't want projects matching this criteria to be deployed but that's another issue.

Ultimately, the architecture doesn't work since Android and WinRT can target x86 and ARM. (VS only support x64 for WinRT desktop apps currently) I haven't looked into exactly how VS2015 does iOS but I imagine it would be similar?

I'm not really sure what the best solution is, but the modules still need the control over whether the line is emit or not, based on the parameters `cfg` and `context`.

**Comment by starkos** [comment] 2016-04-18 15:56
We've never done anything like this, but what we define a new hook which is called by the VS exporter, with the intention of it being overridden by modules?

```lua
-- base implementation assumes nothing is deployable (for now)
function m.isDeployable(context)
   return false
end

function m.deploy0(cfg, context, emit)
  if m.isDeployable(context) then
    p.w('{%s}.%s.Deploy.0 = %s|%s', context.prj.uuid, context.descriptor, context.platform, context.architecture)
  end
end
```

A module would override and look at the `context` to figure things out:

```lua
p.override(p.vstudio.vc2010, "isDeployable", function(base, context)
   if doSomethingToCheck(context) then
      return true
   else
      return base(context)
   end
end)
```

Would something like that be workable? I prefer this approach to a static flag as it is more dynamic and less susceptible to order-of-processing issues.

**Comment by samsinsane** [comment] 2016-04-18 23:25
Yeah that should work. Does `context` contain `cfg` or the same set of variables and values?

**Comment by starkos** [comment] 2016-04-19 15:48
I honestly don't know (don't have the full code in front of me). But I'm sure those values are accessible, and we can include them in the arguments to the hook.

**Comment by samsinsane** [comment] 2017-04-19 14:28
Closing this as you can now override `premake.vstudio.sln2005.elements.projectConfigurationPlatforms` and add the deployable entry if required.

**Closed by samsinsane** 2017-04-19 14:28 UTC
