### ISSUE TITLE
CC not defined in Makefile

### ISSUE THREAD

**Issue by aezaqiel** [premake/premake-core#1681] opened 2021-07-30 16:23 UTC
When I generate project file for gmake2, the CC is not defined in the Makefile and I have to manually define CC in each Makefile. Is there something that I need to put in my premake5.lua for it to do it automatically?

I'm on Windows 10 with Mingw-w64.

**Comment by samsinsane** [comment] 2021-07-31 02:36
Duplicate of #1640

**Closed by samsinsane** 2021-07-31 02:36 UTC
Labels: question
