### ISSUE TITLE
toolset("v140") throwing error

### ISSUE THREAD

**Issue by amc522** [premake/premake-core#55] opened 2015-05-07 03:14 UTC
When creating a vs2015 solution, some of my projects (but not all) did not have
```xml
<PlatformToolset>v140</PlatformToolset>
```
I then tried to explicitly set the platform toolset using
```lua
toolset("v140")
```
That caused the following error:
> invalid value 'v140' for toolset

**Comment by starkos** [comment] 2015-05-07 11:12
I'm unable to reproduce this here. Can you provide a small example project that demonstrates one or both of the the issues?

**Comment by amc522** [comment] 2015-05-07 14:57
I am able to reproduce the error with this minimal premake file
```lua
solution "Test"
    language "C++"
    toolset "v140"
```

I am testing on Windows with the alpha 3 binaries.

**Comment by starkos** [comment] 2015-05-07 16:15
Hmm, I don't see any error when I try that code.

> Even if a project has no files, it should still set the platform toolset.

I'm not sure if that's true, actually, I would have to check the default behavior of VS. We have an explicit check in the code to make sure the project actually contains a C/C++ file before adding the PlatformToolset element now.

**Comment by amc522** [comment] 2015-05-07 17:07
Ill try build premake from source and see if I still have the same issue.

In regards to the PlatformToolset being set for projects with no files, it was just a thought. When I open those empty projects in vs2015, I get prompted to upgrade them. It assumes they are 2010 projects.

**Comment by amc522** [comment] 2015-05-07 19:12
Built from source and ```toolset "v140"``` works without any problems.

**Comment by starkos** [comment] 2015-05-11 18:13
Going to go ahead and close this one out as fixed in the source builds. There is another ticket open already to address the missing PlatformToolset elements.

**Closed by starkos** 2015-05-11 18:13 UTC
