### ISSUE TITLE
Error: ...re/release/premake-5.0.0-alpha13/src/base/fileconfig.lua:191: attempt to index a nil value (local 'fcfg')

### ISSUE THREAD

**Issue by FinIsOro** [premake/premake-core#1219] opened 2019-01-09 17:31 UTC
![image](https://user-images.githubusercontent.com/35429720/50916980-18083200-1445-11e9-88bb-ce75f3906960.png)

**Comment by WorldofBay** [comment] 2019-01-10 07:56
that error is caused by #1040 

there's a nil check missing for `fcfg` in `fileconfig.hasFileSettings` as it is done in `fileconfig.hasCustomBuildRule`

try to use gmake2 instead of gmake, that fixes a lot of issues and will replace gmake some day

**Comment by samsinsane** [comment] 2019-01-10 09:06
Resolved with #1221

**Closed by samsinsane** 2019-01-10 09:06 UTC
