### ISSUE TITLE
Premake5

### ISSUE THREAD

**Issue by Carluccio** [premake/premake-core#1265] opened 2019-04-05 05:15 UTC
Sorry, I'm a beginner. How to put in LIBS + = -Wl, -- start-group ... -Wl, -- end-group?
What instructions in premake5.lua?

**Comment by samsinsane** [comment] 2019-04-05 05:53
You can achieve this using [`linkgroups`](https://github.com/premake/premake-core/wiki/linkgroups).

**Comment by Carluccio** [comment] 2019-06-01 14:23
Sorry, but I had abandoned the idea. Now I resume and reopen the topic.
I tried this:
linkgroups "ON"
links {"lib1", "lib2", "lib3", ....}
but it does not work!
Where and how should I put linkgroups?
(I'm a beginner and I use premake5 alpha 14)
regards
Carlo Sala

**Comment by samsinsane** [comment] 2019-06-07 03:06
That's the correct way, what action are you using? I assume `gmake2`?

**Comment by Carluccio** [comment] 2019-06-07 03:26
I use gmake because gmake2 does not read rc files !! (another fault found)
In any case, linkgroups does not work in both cases
regards
Carlo Sala

**Comment by Carluccio** [comment] 2019-06-07 03:48
in gmake2 the rc file is read before the others ... in my case it needs to be read last so that my little program works.
However in this case I will be able to make changes.
regards
Carlo Sala

**Comment by Carluccio** [comment] 2019-06-07 05:28
I have to add another anomaly found:
with Mingw64 targetname does not work; with TDM-GCC instead, it works.
Regards
Carlo Sala

**Comment by samsinsane** [comment] 2019-06-07 06:05
Let's keep this issue focused on your original issue. If you can open new issues for the others instead that would be great, otherwise they're just going to get lost and not fixed.

Are `lib1`, `lib2`, etc all Premake projects or are they external dependencies? I'm not sure if Premake wraps all `links` in the link group options, I'm not sure why not though.

**Comment by Carluccio** [comment] 2019-06-07 06:23
Lib1, lib2, etc. they are wxWidgets libraries, so they are libraries located in the wxWidgets folder.
However, I read the generated .make file and in the "LIBS + =" there are these libraries but they are missing at the beginning: -Wl, - start-group and at the end of the list: -WL, - end-group, as instead I should have expected.
regards
Carlo Sala

**Comment by samsinsane** [comment] 2019-06-07 06:41
Right, I don't believe `linkoptions` wraps all libraries just the Premake ones - this should be fixed.

The issue is that the below assumes that everything else is a system library when some will be precompiled libs. Moving the start/end group lines to below the bottom is probably the best solution. https://github.com/premake/premake-core/blob/b173d0890a43a35b1cda48ef019274fc58b232bb/src/tools/gcc.lua#L470-L475

**Comment by Carluccio** [comment] 2019-06-07 07:45
Yes, I understood the problem, but the inconsistent list order concerns, in my case, only that of the wxWidgets static libraries.
I had however solved by changing the order of listing, and I had found the right one thus solving the problem.
In any case it would have been nice to have "linkgroups" working for these too.
regards
Carlo Sala

**Comment by samsinsane** [comment] 2019-06-07 07:52
> In any case it would have been nice to have "linkgroups" working for these too.

Agreed, that's why I've added the information above, so that if I can't get to it then someone else can move those four lines down the function and ensure that all libraries are within the link group ordering.

**Closed** 2020-02-13 01:28 UTC
