### ISSUE TITLE
HLSL file property configurations  

### ISSUE THREAD

**Issue by GCourtney27** [premake/premake-core#1441] opened 2020-05-02 01:43 UTC
Is there currently a way to edit the hlsl properties for a shader file? i.e. to change the shader type of shader model? #1037 gives a situation similar to what I am looking for but seems to be a global solution for all shader files and does not show a clear example of how to use it.

I currently use visual studio to compile my shaders to .cso files and I need to set certain settings in the properties dialog for them to compile. Upon regenerating the Visual studio solutions, those settings get wiped out and I have to reset them.

**Comment by samsinsane** [comment] 2020-05-03 07:06
Unless I'm misunderstanding, you should be able to do something along the lines of:
```lua
filter { "files:**.hlsl" }
  shadermodel "5.0"
filter { }
```
At a glance of that PR, I'm not sure this will work as intended, so more work might need to be done so you can change the settings on individual files.

**Comment by starkos** [comment] 2020-05-09 13:54
@GCourtney27 did you get a chance to try this out? Any luck?

**Comment by GCourtney27** [comment] 2020-05-09 20:57
Using the code from @samsinsane I was able to come up with a solution. First, I use @samsinsane code to globally change all .hlsl files to shader model 5. Since you can't directly reference a single file with the filter keyword I just target a custom extension for all files of a particular type I want to reference. For example, for all new shaders I use a naming convention that goes: "MyCoolShaderName.pixel.hlsl" for all pixel shaders and "MyCoolShaderName.vertex.hlsl" for vertex shaders and the same goes for tesselation(.tess.hlsl), geometry(.geom.hlsl) shaders and so on. In premake I use `filter { "files:**.pixel.hlsl" }
		shadertype "Pixel"` for pixel shaders and `filter { "files:**.vertex.hlsl" }
		shadertype "Vertex"` for vertex shaders to find all of the shaders with those extensions and change them to their desired type.

**Comment by samsinsane** [comment] 2020-05-10 07:36
> Since you can't directly reference a single file with the filter keyword

You should be able to do this, are you able to provide an example of where this doesn't work? If you can match the file with `files:**.hlsl` then you can match the file with `files:full/path/to/file.hlsl`?

**Comment by GCourtney27** [comment] 2020-05-10 19:08
@samsinsane oops yes are able to do this I was searching with Shader.pixel.hlsl and expecting premake to find it. When I should have been providing the path relative to the premake script. I tried it again and it worked with the full path. This would be helpful if you have a particular file you need to have unique settings for.

**Comment by GCourtney27** [comment] 2020-05-10 19:14
I think adding what we've discussed here to the examples section in the  "filter" topic in the documentation would be helpful for a lot of people looking for this functionality.

**Comment by starkos** [comment] 2020-05-10 19:43
Note that, if it's easier, you can write things like…

```
filter { "files:**/Shader.pixel.hlsl" }
```

…so you don't have to rework your Premake scripts if you decide to rearrange your source tree.

Going ahead and closing this since it seems to be solved. Feel free to continue the conversation if you still have questions.

**Closed by starkos** 2020-05-10 19:43 UTC
Labels: question

**Comment by GCourtney27** [comment] 2020-05-10 19:45
Perfect thanks for your help guys!

**Comment by GCourtney27** [comment] 2020-11-26 00:18
Is there a keyword to import shaders as library files? Like what we did above with shadertype: "Vertex" but with something like shadertype: "Library" I tried Lib, lib, library, and Library and all of them are undefined when running premake.

**Comment by starkos** [comment] 2020-11-27 19:47
Looks like `shadertype` is defined [here](https://github.com/premake/premake-core/blob/master/modules/vstudio/_preload.lua#L55-L70). Not sure if any of those existing values are what you're looking for though?
