### ISSUE TITLE
Generated solutions for D unreadable by Visual Studio

### ISSUE THREAD

**Issue by Straivers** [premake/premake-core#1603] opened 2021-03-26 04:00 UTC
**What seems to be the problem?**
D projects generated by Premake for VS2019 cannot be opened by VisualD.

![image](https://user-images.githubusercontent.com/10258383/112574328-6d318380-8dc4-11eb-997e-64947050fb26.png)

**What did you expect to happen?**
The created solution should contain a project called `t` that contains a single file called `app.d`.

**What have you tried so far?**
Diffing the generated `t.visualdproj` and `test.sln` against that generated by **dub** shows changes that to my untrained eye appear to be minor and adding details to the `premake5.lua` allows a very similar `.visualdproj` file to be generated by Premake.

**How can we reproduce this?**
Given the files and directory structure described below, generate a VS2019 build (`premake5 vs2019`) then attempt to open the solution in VS2019 with VisualD 1.1.0. It should load the solution, but fail to load the project.

**Directory:**
```
test/
    app.d
    premake5.lua
```

**premake5.lua:**
```lua
workspace "test"
    configurations { "debug" }

    project "t"
        kind "ConsoleApp"
        language "D"
        files "**.d"
```

**app.d:**
```
module app;
import std.stdio;
void main() { writeln("o/"); }
```

**What version of Premake are you using?**
premake5 (Premake Build Script Generator) 5.0.0-alpha15

**Comment by starkos** [comment] 2021-03-26 12:04
Our resident D expert—the one who developed the module—hasn't been around of late. We could really use your assistance and identifying the problem and getting a pull request together to fix this.

**Comment by Straivers** [comment] 2021-03-27 05:08
I'd love to, but I'm really busy right now. Coupled with my unfamiliarity with Premake and VisualD's innards, I'm not sure that any assistance would arrive in a timely fashion. I'll be certain to give it a poke as time permits.

**Comment by samsinsane** [comment] 2021-04-09 08:25
Looks like the issue is that this https://github.com/premake/premake-core/blob/954271148cbb36e71db4c5568655e4d65a1c74f3/modules/d/actions/visuald.lua#L177-L178 doesn't work properly anymore. It doesn't look like it's possible to set `toolset "dmd"` either, but you can add to the command line `--dc=dmd` and the project will work again.

**Comment by nickclark2016** [comment] 2021-06-24 02:51
I've got a working fix for this.  I'll clean it up and push it tomorrow.  Tl;dr on it is that I add "dmd", "gdc", and "ldc" as allowed values for "toolset".  There are a few tweaks I have to do in order to support this from the api's internal mechanisms, but it should be good to go.

**Closed** 2021-07-08 10:27 UTC
Labels: bug
