### ISSUE TITLE
C# vs 2010 Name clashes on object code

### ISSUE THREAD

**Issue by Slazanger** [premake/premake-core#419] opened 2016-02-04 09:55 UTC
I have encountered a problem related to name clashes during the build :

My premake solution looks like this :

```
workspace "Test"
configurations { "Debug", "Release"}

-- output locations
location("Intermediate/" .. _ACTION )
objdir ( "Intermediate/" .. _ACTION .. "/obj/%{cfg.buildcfg}/" )
targetname "%{prj.name}_%{cfg.buildcfg}"


project "Test"
    language "c#"
    kind "ConsoleApp"

    files
    {
        "**.cs",
        "**.xaml",
    }


    filter {}
```
And I end up including 2 offending files :

TestFolder1\Test.cs
TestFolder2\Test.cs

each with different namespace however they both compile to the same folder, and as such i get a MSB3105 compiler error stating the source file \Intermediate\vs2010\obj\debug\Test.g.cs was specified more than once in the "Sources" parameter.

I have tried using the filters to set a different objdir for the offending files, using the iles.relpath token in the objfolder however im not having any luck...

Any ideas how i  can resolve this ?

**Comment by Slazanger** [comment] 2016-02-04 10:29
Forgot to add : this is using vs2010 as the action

**Comment by tvandijck** [comment] 2016-02-04 17:07
Do you have a manually crafted visual studio project in which this works? That way we can look at what Microsoft's own IDE uses to avoid the name clash...

**Comment by Slazanger** [comment] 2016-02-08 14:26
[TestApp.zip](https://github.com/premake/premake-core/files/121677/TestApp.zip)

I've attached a simple test app that highlights it... included vs2010 project that builds fine, then premake file which generates the same project but fails to compile.

Thanks,

**Comment by samsinsane** [comment] 2016-02-25 13:31
> included vs2010 project that builds fine, then premake file which generates the same project but fails to compile.

This isn't quite right, the generated files are located in a folder, this is actually the cause of the problems. Remove the `location` line in your `premake5.lua` file and it should work.

This is a limitation with how VS handles C# projects, there's no way to have fine grain control over the intermediate files that are generated by compile items. I spent a couple of hours looking into this and I couldn't find anything to get this going, but my knowledge on the MSBuild system isn't very good.

**Comment by starkos** [comment] 2016-02-25 13:59
Yup, that `location()` call is an issue. Visual Studio requires all sources to be in or under the same directory as the project, so that needs to be `location "TestApp"`. 

I'm not sure about the `objdir()` call (not on a Windows box to test) but you might want to try turning that off and let VS use its defaults, see if that makes any difference.

**Comment by starkos** [comment] 2016-02-25 14:00
Sorry didn't mean to close that…reopening…

**Comment by samsinsane** [comment] 2016-03-08 11:52
Closing this off as the issue is due to VS not handling files outside the current folder (and subfolders). If this issue continues to occur without the `location` call, please feel free to reopen this issue.

**Closed by samsinsane** 2016-03-08 11:52 UTC
